esphome:
  name: multi-ir
  friendly_name: Multi_ir

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lkSavSbH3q1+4R0YwBYMejTFUduRbURDw7izGNOSHyE="

ota:
  - platform: esphome
    password: "2e3dff4ccbb5fa5654c55569c1aa3b05"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Multi-Ir Fallback Hotspot"
    password: "pI905ZM7z2rB"

captive_portal:

globals:
  id: codi_tv1
  type: int
  restore_value: no
  initial_value: '0'

  id: codi_tv2
  type: int
  restore_value: no
  initial_value: '0'

  id: codi_tv3
  type: int
  restore_value: no
  initial_value: '0'

  id: codi_tv4
  type: int
  restore_value: no
  initial_value: '0'

  id: tv_actual
  type: int
  restore_value: no
  initial_value: '1'


remote_receiver:
  pin: 
    number: GPIO15
    inverted: True
    mode: INPUT_PULLUP
  dump: all

remote_transmitter:
  id: IR_TV_1
  pin: GPIO14
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

  id: IR_TV_2
  pin: GPIO12
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

  id: IR_TV_3
  pin: GPIO04
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

  id: IR_TV_4
  pin: GPIO02
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%


button:

  # Selecciono la TV sobre la que vull actuar
  - platform: template
    name: TV1
    id: sel_tv_1
    on_press:
      - globals.set:
          id: tv_actual
          value: '1'

  - platform: template
    name: TV2
    id: sel_tv_2
    on_press:
      - globals.set:
          id: tv_actual
          value: '2'

  - platform: template
    name: TV3
    id: sel_tv_3
    on_press:
      - globals.set:
          id: tv_actual
          value: '3'

  - platform: template
    name: TV4
    id: sel_tv_4
    on_press:
      - globals.set:
          id: tv_actual
          value: '4'

  # Selecció del protocol de comunicació
  # Aixó actua sobre la Tv Seleccionada (vigilar)
  - platform: template
    name: Protocol 01
    # Protocol 1
    id: P01
    on_press:
      then: 
        - lambda: |-
            if (id(tv_actual) = 1) {
            id(codi_tv1) = 1;
            } else if (id(tv_actual) = 2) {
            id(codi_tv2) = 1;
            } else if (id(tv_actual) = 3) {
            id(codi_tv3) = 1;
            } else if (id(tv_actual) = 4) {
            id(codi_tv4) = 1}

  - platform: template
    name: Protocol 02
    # Protocol 2
    id: P02
    on_press:
      then: 
        - lambda: |-
            if (id(tv_actual) = 1) {
            id(codi_tv1) = 2;
            } else if (id(tv_actual) = 2) {
            id(codi_tv2) = 2;
            } else if (id(tv_actual) = 3) {
            id(codi_tv3) = 2;
            } else if (id(tv_actual) = 4) {
            id(codi_tv4) = 2}

  - platform: template
    name: Protocol 03
    # Protocol 3
    id: P03
    on_press:
      then: 
        - lambda: |-
            if (id(tv_actual) = 1) {
            id(codi_tv1) = 3;
            } else if (id(tv_actual) = 2) {
            id(codi_tv2) = 3;
            } else if (id(tv_actual) = 3) {
            id(codi_tv3) = 3;
            } else if (id(tv_actual) = 4) {
            id(codi_tv4) = 3}

 - platform: template
   name: Protocol 04
   # Protocol 4
   id: P04
   on_press:
     then: 
      - lambda: |-
          if (id(tv_actual) = 1) and {
          id(codi_tv1) = 4;
          } else if (id(tv_actual) = 2) {
          id(codi_tv2) = 4;
          } else if (id(tv_actual) = 3) {
          id(codi_tv3) = 4;
          } else if (id(tv_actual) = 4) {
          id(codi_tv4) = 4}


  - platform: template
    name: Boto_1
    on_press:
      then: 
      - lambda: |-
          if (id(tv_actual) = 1) {
          id(codi_tv1) = 4;
          } else if (id(tv_actual) = 2) {
          id(codi_tv2) = 4;
          } else if (id(tv_actual) = 3) {
          id(codi_tv3) = 4;
          } else if (id(tv_actual) = 4) {
          id(codi_tv4) = 4}
        
      - remote_transmitter.transmit_rc6:
          transmitter_id: # Variable global IR_TV_1
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_2
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_3
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_4
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_5
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_6
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_7
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_8
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_9
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_0
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_POWER
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_CH_MES
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_CH_MENYS
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_VOL_MENYS
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_VOL_MES
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

  - platform: template
    name: RC6_Boto_MUTE
    on_press:
      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C


interval:
  - interval: 20sec
    then:
      - logger.log: "Tiro infraroig"

      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

      - delay: 2sec

      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

      - delay: 2sec

      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C

      - delay: 2sec    

      - remote_transmitter.transmit_rc6:
          address: 0x00
          command: 0x0C
 
